title: "The Gospel"
hero_banner_title: "The Gospel"
footer_text: "© 2024 christdiedforoursins. All rights reserved."
contact_email: "christdiedforoursins7@gmail.com"
sass:
  sass_dir: _sass
  style: compressed
